function ImaGIN(cmd)
% Starts the ImaGIN toolbox GUI (spm toolbox).

% -=============================================================================
% This function is part of the ImaGIN software: 
% https://f-tract.eu/
%
% This software is distributed under the terms of the GNU General Public License
% as published by the Free Software Foundation. Further details on the GPLv3
% license can be found at http://www.gnu.org/copyleft/gpl.html.
%
% FOR RESEARCH PURPOSES ONLY. THE SOFTWARE IS PROVIDED "AS IS," AND THE AUTHORS
% DO NOT ASSUME ANY LIABILITY OR RESPONSIBILITY FOR ITS USE IN ANY CONTEXT.
%
% Copyright (c) 2000-2017 Inserm U1216
% =============================================================================-
%
% Authors: Olivier David, 2010-2017
%          Francois Tadel, 2017
 
%-Set ImaGIN path
%-----------------------------------------------------------------------
% Make sure the main ImaGIN folder is at the top of the path
ImaGINdir = fileparts(which(mfilename));
addpath(ImaGINdir, '-BEGIN'); 
% List of folders to add
toolboxDir = {'external','toolbox'}; % in reverse order of priority
for i = 1:length(toolboxDir)
    nextdir = fullfile(ImaGINdir,toolboxDir{i});
    % Check that directory exist
    if ~isdir(nextdir)
        error(['Directory "' toolboxDir{i} '" does not exist in the ImaGIN path.' 10 ...
               'Please re-install ImaGIN.']);
    end
    % Recursive search for subfolders in each main folder
    P = genpath(nextdir);
    % Add directory and subdirectories
    addpath(P, '-BEGIN');
end


%-Switch for specific commands
%-----------------------------------------------------------------------
if (nargin >= 1) && ~isempty(cmd)
    switch lower(cmd)
        case 'deploy'
            addpath(fullfile(ImaGINdir, 'deploy'));
            ImaGIN_deploy
            return;
    end
end


%-Initializes SPM
%-----------------------------------------------------------------------
% Configure SPM
spm('Defaults','EEG')
% Vis='on';
Modalities = {'PET','FMRI','EEG'};
%-Close any existing 'Menu' 'Tag'ged windows
delete(spm_figure('FindWin','Menu'))

%-Get size and scalings and create Menu window
%-----------------------------------------------------------------------
WS   = spm('WinScale');				%-Window scaling factors
FS   = spm('FontSizes');			%-Scaled font sizes
PF   = spm_platform('fonts');			%-Font names (for this platform)
Rect = spm('WinSize','Menu','raw').*WS;		%-Menu window rectangle

[SPMver,SPMc] = spm('Ver','',1);

Fmenu = figure('IntegerHandle','off',...
	'Name',sprintf('%s%s',spm('ver'),spm('GetUser',' (%s)')),...
	'NumberTitle','off',...
	'Tag','Menu',...
	'Position',Rect,...
	'Resize','off',...
	'Color',[1 1 1]*.8,...
	'UserData',struct('SPMver',SPMver,'SPMc',SPMc),...
	'MenuBar','none',...
	... 'DefaultTextFontName',PF.helvetica,...
	'DefaultTextFontSize',FS(8),...
	... 'DefaultUicontrolFontName',PF.helvetica,...
	'DefaultUicontrolFontSize',FS(8),...
	'DefaultUicontrolInterruptible','on',...
	'Renderer','painters',...
	'Visible','on', ...
    'CloseRequestFcn', 'spm(''Quit'')');

%-Frames and text
%-----------------------------------------------------------------------
uicontrol(Fmenu,'Style','Frame','BackgroundColor',spm('Colour'),...
	'Position',[010 145 380 295].*WS)

uicontrol(Fmenu,'Style','Frame',...
	'Position',[020 340 360 90].*WS)

uicontrol(Fmenu,'Style','Text',...
  'String','Data definition',...
	'Position',[025 410 350 020].*WS,...
	'ForegroundColor','k',...
    'FontAngle','Italic',...
	'HorizontalAlignment','Left',...
    'Tag', 'EEG')

uicontrol(Fmenu,'Style','Frame',...
	'Position',[020 295 360 40].*WS, 'Tag', 'EEG')

uicontrol(Fmenu,'Style','Text',...
	'String','Analysis',...
	'Position',[025 315 350 020].*WS,...
	'ForegroundColor','k',...
    'FontAngle','Italic',...
	'HorizontalAlignment','Left',...    
	'Tag', 'EEG')

uicontrol(Fmenu,'Style','Frame',...
	'Position',[020 200 360 90].*WS,...
    'Tag', 'EEG')

uicontrol(Fmenu,'Style','Text',...
    'String','Display',...
	'Position',[025 270 350 020].*WS,...
	'ForegroundColor','k',...
    'FontAngle','Italic',...
	'HorizontalAlignment','Left',...
	'Tag', 'EEG')

uicontrol(Fmenu,'Style','Frame',...
	'Position',[020 155 360 40].*WS,...
    'Tag', 'EEG')
uicontrol(Fmenu,'Style','Text',...
	'String','Inference',...
	'Position',[025 175 350 020].*WS,...
	'ForegroundColor','k',...
	'FontAngle','Italic',...
	'HorizontalAlignment','Left',...
    'Tag', 'EEG')

uicontrol(Fmenu,'Style','Text',...
	'String','SPM Intracerebral EEG Toolbox',...
	'ToolTipString','modality & defaults set for EEG/MEG',...
	'ForegroundColor',[1 1 1]*.6,'BackgroundColor',[1 1 1]*.8,...
	'FontAngle','Italic','FontWeight','Normal','FontSize',FS(10),...
	'HorizontalAlignment','center',...
	'Position',[020 122 360 020].*WS,...
	'Tag','EEG','Visible','on')

% Utilities frames and text
%-----------------------------------------------------------------------
uicontrol(Fmenu,'Style','Frame',...
	'BackgroundColor',spm('Colour'),...
	'Position',[010 010 380 112].*WS)

uicontrol(Fmenu,'Style','Text','String',SPMc,...
	'ToolTipString',SPMc,...
	'ForegroundColor',[1 1 1]*.6,...
	'BackgroundColor',[1 1 1]*.8,...
	'FontName',PF.times,...
	'HorizontalAlignment','center',...
	'Position',[020 002 360 008].*WS)

%-Objects with Callbacks - main spm_*_ui.m routines
%=======================================================================

%-Data
%-----------------------------------------------------------------------
uicontrol(Fmenu,'Style','PopUp',...
    'String','Import|  Convert|  Events|  Electrodes positions|  Bipolar montage',...
	'Position',[035 380 100 030].*WS,...
    'FontSize', FS(9), ...
	'ToolTipString', 'Convert data in SPM EEG format',...
    'CallBack','spm(''PopUpCB'',gcbo)',...
	'UserData',{'ImaGIN_spm_eeg_converteeg2mat;','ImaGIN_Events;','ImaGIN_Electrode;','ImaGIN_BipolarMontage;'},...
    'Tag', 'EEG');

uicontrol(Fmenu,'Style','PopUp',...
    'String','Preprocess|  Bandpass filter|  Notch filter|  Downsample',...
	'Position',[150 380 100 030].*WS,... 
    'FontSize', FS(9), ...
	'ToolTipString','Other preprocessing functions',...
    'CallBack','spm(''PopUpCB'',gcbo)',...
	'UserData',{'ImaGIN_BPFilter;','ImaGIN_NotchFilter;','ImaGIN_spm_eeg_downsample;'},...
    'Tag', 'EEG')

uicontrol(Fmenu,'Style','PopUp',...
    'String','Display|  ImaGIN viewer|  SPM viewer',...
	'Position',[265 380 100 030].*WS,... 
    'FontSize', FS(9), ...
	'ToolTipString','Other preprocessing functions',...
    'CallBack','spm(''PopUpCB'',gcbo)',...
	'UserData',{'ImaGIN_DispData;','spm_eeg_review;'},...
    'Tag', 'EEG')

uicontrol(Fmenu,'String','Time zero',...
    'Position',[035 345 100 030].*WS,...
    'ToolTipString','Define time origin compared to a pre-defined event',...
    'UserData','ImaGIN_TimeZero',...
    'CallBack','ImaGIN_TimeZero;',...
    'Tag', 'EEG',...
    'Visible','on');

uicontrol(Fmenu,'String','Epoch',...
    'Position',[150 345 100 030].*WS,... 
	'ToolTipString','Select a time window according to pre-defined events and overwrite a new (smaller) data set',...
    'UserData','ImaGIN_Crop',...
	'CallBack','ImaGIN_Crop;',...
    'Tag', 'EEG',...
    'Visible','on');

uicontrol(Fmenu,'String','Montage',...
    'Position',[265 345 100 030].*WS,...
	'ToolTipString',['Create a new SPM montage file from two text files' 10 '(names and positions of the electrodes)'],...
    'UserData','ImaGIN_Montage',...
	'CallBack','ImaGIN_Montage(1);',...
    'Tag', 'EEG',...
    'Visible','on');

% Spatial EEG
%-----------------------------------------------------------------------
uicontrol(Fmenu,'Style','PopUp',...
    'String','FFT|  Compute',...
	'Position',[25 290 50 030].*WS,...
	'ToolTipString','Power spectrum density',...
    'CallBack','spm(''PopUpCB'',gcbo)',...
	'UserData',{'ImaGIN_FFT;'},...
    'Tag', 'EEG')

uicontrol(Fmenu,'Style','PopUp',...
    'String','Time Freq|  Compute|  Normalise|  Rescale|  Average',...
	'Position',[85 290 65 030].*WS,...
	'ToolTipString','Time frequency analysis (power and synchrony)',...
    'CallBack','spm(''PopUpCB'',gcbo)',...
	'UserData',{'ImaGIN_spm_eeg_tf;','ImaGIN_NormaliseTF;','ImaGIN_RescaleTF;','ImaGIN_AverageTF;'},...
    'Tag', 'EEG')

uicontrol(Fmenu,'Style','PopUp',...
    'String','Causality|  Compute|  Average',...
	'Position',[160 290 65 030].*WS,...
	'ToolTipString','Causality analysis',...
    'CallBack','spm(''PopUpCB'',gcbo)',...
	'UserData',{'ImaGIN_causality_compute;','ImaGIN_causality_average;'},...
    'Tag', 'EEG')

uicontrol(Fmenu,'Style','PopUp',...
    'String','Firing rate|  Compute',...
	'Position',[235 290 65 030].*WS,...
	'ToolTipString','Firing rate',...
    'CallBack','spm(''PopUpCB'',gcbo)',...
	'UserData',{'ImaGIN_spike_compute;'},...
    'Tag', 'EEG')

uicontrol(Fmenu,'String','3D interpolation',...
    'Position',[310 300 65 030].*WS,...
	'ToolTipString', '3D interpolation of EEG intracerebral data',...
	'UserData','ImaGIN_spm_eeg_TF_images_3D;',...
	'CallBack','ImaGIN_spm_eeg_TF_images_3D;',...
	'Visible','on',...
    'Tag','EEG')

% Statistical EEG
%-----------------------------------------------------------------------
uicontrol(Fmenu,'String','Montage',...
	'Position',[25 240 110 030].*WS,...
	'ToolTipString','Display montage',...
	'UserData','ImaGIN_Montage',...
	'CallBack','ImaGIN_Montage(2);',...
    'Tag', 'EEG');

uicontrol(Fmenu,'String','Data',...
	'Position',[25 205 110 030].*WS,...
	'ToolTipString','Display data',...
	'UserData','ImaGIN_DispData',...
	'CallBack','ImaGIN_DispData;',...
    'Tag', 'EEG');

uicontrol(Fmenu,'String','Time Frequency',...
	'Position',[145 240 110 030].*WS,...
	'ToolTipString','Display time frequency analysis',...
	'UserData','ImaGIN_DispTF',...
	'CallBack','ImaGIN_DispTF',...
    'Tag', 'EEG');

uicontrol(Fmenu,'String','Brain overlay',...
    'Position',[145 205 110 030].*WS,...
	'ToolTipString', '3D EEG intracerebral data overlaid on a brain',...
	'UserData','ImaGIN_Disp3D;',...
	'CallBack','ImaGIN_Disp3D;',...
	'Visible','on',...
    'Tag','EEG')

uicontrol(Fmenu,'String','Causality',...
	'Position',[265 240 110 030].*WS,...
	'ToolTipString','Display causality analysis',...
	'UserData','ImaGIN_DispCausality',...
	'CallBack','ImaGIN_DispCausality',...
    'Tag', 'EEG');

uicontrol(Fmenu,'String','Results',...
	'Position',[130 160 130 030].*WS,...
    'FontSize',FS(9), ...
	'ToolTipString','Inference and regional responses etc.',...
	'UserData','spm_results_ui',...
	'CallBack','[hReg,xSPM,SPM] = spm_results_ui;',...
    'Tag', 'EEG');

% -Utility buttons (first line)
% -----------------------------------------------------------------------
uicontrol(Fmenu,'Style','PopUp',...
    'String','Display...|images|M/EEG',...
	'Position',[020 088 082 024].*WS,...
	'ToolTipString','orthogonal sections and M/EEG display',...
    'CallBack','spm(''PopUpCB'',gcbo)',...
	'UserData',{'spm_image;','spm_eeg_review;'},...
    'Tag', 'EEG')

uicontrol(Fmenu,'String','Check Reg',...
	'Position',[112 088 083 024].*WS,...
	'ToolTipString','check image registration',...
	'UserData','spm_check_registration',...
	'CallBack','spm_check_registration;')

uicontrol(Fmenu,'Style','PopUp',...
	'String',Modalities,...
	'ToolTipString','change modality PET<->fMRI<->EEG',...
	'Tag','Modality',...
	'Position',[298 088 082 024].*WS,...
	'CallBack',[...
        'if get(gco,''Value'')==1;',...
        'spm ''PET'';',...
        'elseif get(gco,''Value'')==2;',...
        'spm ''FMRI'';',...
        'elseif get(gco,''Value'')==3;',...
        'spm ''EEG'';',...
        'end'],...
    'UserData','SPM_Modality',...
	'Interruptible','off')


%-Utility buttons (second line)
%-----------------------------------------------------------------------

uicontrol(Fmenu,'String','Seizure detect',...
	'Position',[020 054 083 024].*WS,...
	'ToolTipString','Detect seizure and write a time series in a new channel',...
	'UserData','ImaGIN_SeizureDetect',...
	'CallBack','ImaGIN_SeizureDetect;')

uicontrol(Fmenu,'String','Epileptogenicity',...
	'Position',[020 020 083 024].*WS,...
	'ToolTipString','Compute epileptogenicity on SEEG',...
	'UserData','ImaGIN_Epileptogenicity',...
	'CallBack','ImaGIN_Epileptogenicity;')

uicontrol(Fmenu,'String','Stim detect',...
	'Position',[112 054 083 024].*WS,...
	'ToolTipString','Detect stimulation and write events in a text file',...
	'UserData','ImaGIN_StimDetect',...
	'CallBack','ImaGIN_StimDetect;')

uicontrol(Fmenu,'String','Artefact correct',...
	'Position',[112 020 083 024].*WS,...
	'ToolTipString','Correct stimulation artefacts',...
	'UserData','ImaGIN_ArtefactCorrectionModel',...
	'CallBack','ImaGIN_ArtefactCorrectionModel;')

uicontrol(Fmenu,'String','Implantation',...
	'Position',[205 020 083 024].*WS,...
	'ToolTipString','Prepare montage from postop MRI',...
	'UserData','ImaGIN_MRImplantation',...
	'CallBack','ImaGIN_MRImplantation;')

uicontrol(Fmenu,'String','Quit',...
	'Position',[298 020 082 024].*WS,...
	'ToolTipString','exit SPM',...
	'ForeGroundColor','r',...
	'Interruptible','off',...
	'UserData','QuitSPM',...
	'CallBack','spm(''Quit''), clear all')




